/**
 * HOMEFY.PK — Category seed data mapped to StoreCraft Category schema.
 * Source: Shopify collections (19 Jul 2026). Multi-parent via `parentSlugs`.
 *
 * Field mapping from the Downloads pack → StoreCraft:
 *   image (string)     → image.url
 *   metaTitle          → seo.metaTitle
 *   isActive           → status: "active"
 *   isFeatured         → isFeatured + featured + showOnHomepage + showInNav
 *   parentSlugs        → parents[] + parentCategory (first)
 */

export const parents = [
  {
    name: "Exterior",
    slug: "exterior",
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/splitter.webp?v=1773684833",
    description:
      "Upgrade your car's look — body kits, splitters, spoilers, mirror covers, louvers and exhaust styling.",
    metaTitle: "Car Exterior Accessories in Pakistan | Homefy.pk",
    sortOrder: 1,
    isFeatured: true,
  },
  {
    name: "Interior",
    slug: "interior",
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/steering.webp?v=1767353058",
    description: "Steering covers, multimedia controls, ambient lighting and cabin decoration.",
    metaTitle: "Car Interior Accessories in Pakistan | Homefy.pk",
    sortOrder: 2,
    isFeatured: true,
  },
  {
    name: "LED & Lighting",
    slug: "led-lighting",
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/4_light.webp?v=1767350891",
    description: "SOS flashers, LED headlights, indicators and interior ambient lights.",
    metaTitle: "Car LED Lights in Pakistan | Homefy.pk",
    sortOrder: 3,
    isFeatured: true,
  },
  {
    name: "Carbon Fiber",
    slug: "carbon-fiber",
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/IMG_0285_1.webp?v=1780170415",
    description: "Signature carbon fiber styling — trims, mirror covers, interior and exterior upgrades.",
    metaTitle: "Carbon Fiber Car Accessories in Pakistan | Homefy.pk",
    sortOrder: 4,
    isFeatured: true,
  },
  {
    name: "Car Care & Safety",
    slug: "car-care-safety",
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/cc.jpg?v=1767355100",
    description: "Cleaning products, emergency and safety essentials.",
    metaTitle: "Car Care & Safety Products in Pakistan | Homefy.pk",
    sortOrder: 5,
    isFeatured: false,
  },
  {
    name: "Universal Accessories",
    slug: "universal-accessories",
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/hand_geszture.webp?v=1767357165",
    description: "Fit-any-car accessories — caliper covers, HUDs, gadgets and more.",
    metaTitle: "Universal Car Accessories in Pakistan | Homefy.pk",
    shopifyHandle: "universal-car-accessories",
    shopifyId: "gid://shopify/Collection/305065820219",
    sortOrder: 6,
    isFeatured: true,
  },
];

export const children = [
  {
    name: "Body Kits & Extensions",
    slug: "body-kits-extensions",
    parentSlugs: ["exterior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/Splitter_Dotted.png?v=1779824466",
    shopifyHandle: "body-kits-extensions",
    shopifyId: "gid://shopify/Collection/310539976763",
    sortOrder: 1,
  },
  {
    name: "Splitters & Side Skirts",
    slug: "splitters-side-skirts",
    parentSlugs: ["exterior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/splitter.webp?v=1773684833",
    metaTitle: "Car Splitters & Side Skirts | Homefy.pk",
    shopifyHandle: "car-splitters-side-skirts",
    shopifyId: "gid://shopify/Collection/305065427003",
    sortOrder: 2,
  },
  {
    name: "Spoilers & Diffusers",
    slug: "spoilers-diffusers",
    parentSlugs: ["exterior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/spoiler.webp?v=1767356479",
    shopifyHandle: "car-spoilers-diffusers",
    shopifyId: "gid://shopify/Collection/305065623611",
    sortOrder: 3,
  },
  {
    name: "Side Mirror Covers",
    slug: "side-mirror-covers",
    parentSlugs: ["exterior", "carbon-fiber"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/side_mirror.webp?v=1767352595",
    metaTitle: "Carbon Fiber Side Mirror Covers | Homefy.pk",
    shopifyHandle: "carbon-fiber-side-mirror-covers",
    shopifyId: "gid://shopify/Collection/305064312891",
    sortOrder: 4,
  },
  {
    name: "Quarter Window Louvers",
    slug: "quarter-window-louvers",
    parentSlugs: ["exterior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/louvers.webp?v=1767354329",
    shopifyHandle: "car-quarter-window-louvers",
    shopifyId: "gid://shopify/Collection/305064771643",
    sortOrder: 5,
  },
  {
    name: "Exhaust Systems & Tips",
    slug: "exhaust-systems-tips",
    parentSlugs: ["exterior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/tip.webp?v=1767369593",
    shopifyHandle: "car-exhaust-systems-tips",
    shopifyId: "gid://shopify/Collection/305074995259",
    sortOrder: 6,
  },
  {
    name: "Steering Wheel Covers",
    slug: "steering-wheel-covers",
    parentSlugs: ["interior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/steering.webp?v=1767353058",
    shopifyHandle: "car-steering-wheel-covers",
    shopifyId: "gid://shopify/Collection/305064542267",
    sortOrder: 1,
  },
  {
    name: "Multimedia Steering Controls",
    slug: "multimedia-steering-controls",
    parentSlugs: ["interior"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/IMG-0972.jpg?v=1782756874",
    shopifyHandle: "multimedia-steering-controls",
    shopifyId: "gid://shopify/Collection/311911186491",
    sortOrder: 2,
  },
  {
    name: "Air Freshener & Decoration",
    slug: "air-freshener-decoration",
    parentSlugs: ["interior"],
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/aeroplane2_e48b692e-b9c9-4340-8880-d376a9d81384.jpg?v=1767815096",
    shopifyHandle: "air-freshner-and-decoration",
    shopifyId: "gid://shopify/Collection/305276682299",
    sortOrder: 3,
  },
  {
    name: "Interior Lights",
    slug: "interior-lights",
    parentSlugs: ["interior", "led-lighting"],
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/interior_light_2a124971-ac72-44c0-bb63-73c6ce2ea6d4.webp?v=1767714224",
    shopifyHandle: "interior-light",
    shopifyId: "gid://shopify/Collection/305277665339",
    sortOrder: 4,
  },
  {
    name: "SOS & Flasher LED Lights",
    slug: "sos-flasher-led-lights",
    parentSlugs: ["led-lighting"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/4_light.webp?v=1767350891",
    shopifyHandle: "sos-flasher-led-lights",
    shopifyId: "gid://shopify/Collection/305046913083",
    sortOrder: 1,
  },
  {
    name: "LED Headlights & Bulbs",
    slug: "led-headlights-bulbs",
    parentSlugs: ["led-lighting"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/fog_light.webp?v=1767368087",
    shopifyHandle: "led-headlights-bulbs",
    shopifyId: "gid://shopify/Collection/305073979451",
    sortOrder: 2,
  },
  {
    name: "LED Indicator Lights",
    slug: "led-indicator-lights",
    parentSlugs: ["led-lighting"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/turn_light.webp?v=1767368236",
    shopifyHandle: "led-indicator-lights",
    shopifyId: "gid://shopify/Collection/305074044987",
    sortOrder: 3,
  },
  {
    name: "Carbon Fiber Accessories",
    slug: "carbon-fiber-accessories",
    parentSlugs: ["carbon-fiber"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/IMG_0285_1.webp?v=1780170415",
    metaTitle: "Carbon Fiber Car Accessories – Shop Online | Homefy.pk",
    shopifyHandle: "carbon-fiber-car-accessories-shop-online-homefy-pk",
    shopifyId: "gid://shopify/Collection/310666788923",
    sortOrder: 1,
  },
  {
    name: "Car Care & Cleaning",
    slug: "car-care-cleaning",
    parentSlugs: ["car-care-safety"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/cc.jpg?v=1767355100",
    shopifyHandle: "car-care-cleaning-products",
    shopifyId: "gid://shopify/Collection/305065033787",
    sortOrder: 1,
  },
  {
    name: "Emergency & Safety",
    slug: "emergency-safety",
    parentSlugs: ["car-care-safety"],
    imageUrl: "https://cdn.shopify.com/s/files/1/0651/9560/6075/collections/robe.jpg?v=1767357771",
    shopifyHandle: "car-emergency-safety-products",
    shopifyId: "gid://shopify/Collection/305066246203",
    sortOrder: 2,
  },
];
