/**
 * Product CSV column contract (import + export + template).
 * Pipe "|" separates lists (categories, keywords, tags, image URLs).
 */
export const PRODUCT_CSV_HEADERS = [
  "name",
  "slug",
  "articleNo",
  "status",
  "featured",
  "newArrival",
  "isDeal",
  "isUniversal",
  "categorySlugs",
  "shortDescription",
  "longDescription",
  "regularPrice",
  "salePrice",
  "costPerItem",
  "sku",
  "quantity",
  "trackInventory",
  "allowBackorder",
  "lowStockThreshold",
  "weight",
  "weightUnit",
  "imageUrls",
  "tags",
  "vendor",
  "productType",
  "condition",
  "partNumber",
  "ean",
  "metaTitle",
  "metaDescription",
  "metaKeywords",
];

export const PRODUCT_CSV_SAMPLE_ROWS = [
  {
    name: "Universal Front Bumper Splitter ABS 4PCS",
    slug: "universal-front-bumper-splitter-abs-4pcs",
    articleNo: "CC-EXT-001",
    status: "active",
    featured: "true",
    newArrival: "true",
    isDeal: "false",
    isUniversal: "true",
    categorySlugs: "exterior|body-kits-extensions|splitters-side-skirts",
    shortDescription: "Universal ABS front bumper splitter set — 4 pieces.",
    longDescription:
      "<p>Upgrade your front bumper with this universal ABS splitter kit. Includes left, right and center pieces.</p>",
    regularPrice: "4500",
    salePrice: "3999",
    costPerItem: "2200",
    sku: "CC-EXT-001",
    quantity: "25",
    trackInventory: "true",
    allowBackorder: "false",
    lowStockThreshold: "5",
    weight: "1.2",
    weightUnit: "kg",
    imageUrls:
      "https://cdn.example.com/splitter-1.webp|https://cdn.example.com/splitter-2.webp",
    tags: "splitter|exterior|universal",
    vendor: "Homefy",
    productType: "Accessory",
    condition: "new",
    partNumber: "SPL-UNI-4P",
    ean: "",
    metaTitle: "Buy Universal Front Bumper Splitter in Pakistan | Homefy.pk",
    metaDescription:
      "Shop universal ABS front bumper splitter 4PCS online in Pakistan. Cash on Delivery. Fast shipping.",
    metaKeywords: "front bumper splitter|car splitter pakistan|ABS body kit",
  },
  {
    name: "Carbon Fiber Side Mirror Cover Pair",
    slug: "carbon-fiber-side-mirror-cover-pair",
    articleNo: "CC-CF-014",
    status: "active",
    featured: "false",
    newArrival: "false",
    isDeal: "true",
    isUniversal: "false",
    categorySlugs: "carbon-fiber|side-mirror-covers",
    shortDescription: "Gloss carbon-look side mirror covers — pair.",
    longDescription: "<p>Easy clip-on mirror covers with carbon fiber look finish.</p>",
    regularPrice: "2800",
    salePrice: "2499",
    costPerItem: "1100",
    sku: "CC-CF-014",
    quantity: "12",
    trackInventory: "true",
    allowBackorder: "false",
    lowStockThreshold: "3",
    weight: "0.4",
    weightUnit: "kg",
    imageUrls: "https://cdn.example.com/mirror-cover.webp",
    tags: "carbon|mirror|exterior",
    vendor: "Homefy",
    productType: "Accessory",
    condition: "new",
    partNumber: "MC-CF-PAIR",
    ean: "",
    metaTitle: "Carbon Fiber Side Mirror Covers Pakistan | Homefy.pk",
    metaDescription:
      "Buy carbon fiber look side mirror cover pair online in Pakistan at Homefy.pk.",
    metaKeywords: "side mirror cover|carbon mirror cover pakistan",
  },
];
